---
title: "bm2 hw4"
author: "Roxy Zhang"
date: "3/1/2022"
output: github_document
---

```{r}
library(tidyverse)
library (nnet) # multinom
library(MASS) # polr
```


## Question 1

```{r}
data <- c(65, 34, 54, 47, 100, 100,
         130, 141, 76, 116, 111, 191,
         67, 130, 48, 105, 62, 104)

table <- array(
  data = data, 
  dim = c(2, 3, 3),
  dimnames = list(Contact = c("Low", "High"),
            Response = c("Low satisfaction", "Medium Satisfaction", "High Satisfaction"),
            Area = c("Tower block", "Apartment", "House")))

ftable(table)
```

```{r}
# test on levels of satisfaction and contact with other residents
contact <- margin.table(table, margin =c(1, 2))

chisq.test(contact)

# test on levels of satisfaction and type of housing
house <- margin.table(table, margin =c(2, 3))

chisq.test(house)
```


## Question 2

```{r}
data_full <- data.frame(low = as.vector(table[,1,]),
                       medium = as.vector(table[,2,]),
                       high = as.vector(table[,3,]),
                       contact_dummy = rep(c(1, 2), 3),
                       house_dummy = rep(c(2, 1, 3), each = 2))
```

```{r}
# model 1 - without interaction
m1 <- multinom(cbind(data_full$low, data_full$medium, data_full$high)
~ factor(contact_dummy) + factor(house_dummy), data = data_full)

summary(m1)

exp(coef(m1))
exp(confint(m1))

# model 2 - with interaction
m2 <- multinom(cbind(data_full$low, data_full$medium, data_full$high)
~ factor(contact_dummy) +  factor(house_dummy) + factor(contact_dummy)*factor(house_dummy), data = data_full)

summary(m2)

exp(coef(m2))
exp(confint(m2))

# likelihood ratio test
TS1 = deviance(m1) - deviance(m2)
p1= 1 - pchisq(TS1, 4)


# goodness of fit
pihat <- predict(m1, type = "probs")
m <- rowSums(data_full[,1:3])
res.pearson <- (data_full[,1:3]-pihat*m)/sqrt(pihat*m)
G.stat <- sum(res.pearson^2)
p4 <- 1-pchisq(G.stat, (6-4)*(3-1))
```


## Question 3

```{r}
freq <- c(data_full$low, data_full$medium, data_full$high)
res <- c(rep(c("L", "M", "H"), c(6, 6, 6)))
res <- factor(res, levels = c("L", "M", "H"), ordered = T)
data_ord <- data.frame(res = res, int = rep(data_full$contact_dummy, 3),
cate = rep(data_full$house_dummy, 3), freq = freq)

# proportional odds model
m5 <- polr(res ~ factor(int) + factor(cate), data_ord,
weights = freq, method = "logistic")

summary(m5)
exp(coef(m5))

m6 <- polr(res ~ factor(cate), data_ord, weights = freq)
TS5 <- deviance(m6) - deviance(m5)
p5<- 1-pchisq(TS5, 1)

m7 <- polr(res ~ factor(int), data_ord, weights = freq)
TS6 <- deviance(m7) - deviance(m5)
p6<- 1-pchisq(TS6, 2)

# Pearson Chi-Square residuals from proportional odds model
pihat <- predict(m5, type = "probs")
m <- rowSums(data_full[,1:3])
res.pearson <- ((data_full[,1:3]-pihat*m)/sqrt(pihat*m)) %>%
  round(.,2) %>%
  as.data.frame()
```

